### ISSUE TITLE
愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif>

### ISSUE THREAD

**Issue by imliubo** [david-pzh/A-Eye#1]
Hi @david-pzh ,
先给大佬点个:thumbsup:，感谢开源:heart:。
希望可以试用一个月，顺带帮大佬写几篇简单的入门教程，太深奥的可能也写不了:joy:。
我也在多个平台有分享文章，并且代码都是开源的，也非常认同大佬的开源精神：

* [知乎-IAMLIUBO的神奇物联网之旅](https://zhuanlan.zhihu.com/imliubo-magic-IoT-Tutorial)
* [微雪课堂-树莓派&littleVGL](http://www.waveshare.net/study/portal.php?mod=list&catid=66)
* [电子芯吧客-树莓派&wukong-robot](https://www.icxbk.com/article/authorhome?uid=294040)
* [bilibili-一些个人录制的小教程等等](https://space.bilibili.com/31532108)

对大佬做的这个非常mini的小板非常的感兴趣，自从看了大佬画的小板，对某宝上卖的的K210的板子都提不起兴趣来了:disappointed_relieved:。。。因为感觉确实没有一点设计美学，不然可能就已经从某宝入手了。

最后？希望梦想成真？:yum:

**Comment by peng-zhihui** [comment]
你好呀，感谢关注，看了你写的东西很不错的~
AEye你感兴趣的话我送一个焊好的板子给你吧，正好我这边还有两块多的。教程你愿意分享的话可以写好给我，我帮你在github上添加引用， 也可以在知乎上发到我的专栏帮你推广。


有问题可以多交流，祝生活愉快~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"IAMLIUBO"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 下午3:57
收件人:&nbsp;"david-pzh/A-Eye"<A-Eye@noreply.github.com&gt;;
抄送:&nbsp;"593245898"<593245898@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[david-pzh/A-Eye] :runner:愿意分享经验、文章报名咯:sparkles::sparkles:<我不会承认我是为了得到一块PCB！ 滑稽.gif&gt; (#1)




Hi @david-pzh ,
 先给大佬点个👍，感谢开源❤️。
 希望可以试用一个月，顺带帮大佬写几篇简单的入门教程，太深奥的可能也写不了😂。
 我也在多个平台有分享文章，并且代码都是开源的，也非常认同大佬的开源精神：
  
知乎-IAMLIUBO的神奇物联网之旅
 
微雪课堂-树莓派&amp;littleVGL
 
电子芯吧客-树莓派&amp;wukong-robot
 
bilibili-一些个人录制的小教程等等
  
对大佬做的这个非常mini的小板非常的感兴趣，自从看了大佬画的小板，对某宝上卖的的K210的板子都提不起兴趣来了😥。。。因为感觉确实没有一点设计美学，不然可能就已经从某宝入手了。
 
最后？希望梦想成真？😋

**Comment by imliubo** [comment]
Hi @david-pzh ,
感谢感谢，我会努力写好的，邮寄方式已经给大佬发邮件了(一封来自十个月前的邮件回复:laughing:)。
Have a nice day!:sunglasses:

**Comment by peng-zhihui** [comment]
ok，这两天会给你发过去

发自我的iPhone

**Comment by iamtwvl** [comment]
？？？中奖了？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"稚晖"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 晚上6:52
收件人:&nbsp;"david-pzh/A-Eye"<A-Eye@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&gt; (#1)



ok，这两天会给你发过去
 
 发自我的iPhone
 
 &gt; 在 2019年12月28日，下午11:19，IAMLIUBO <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; Hi @david-pzh ,
 &gt; 感谢感谢，我会努力写好的，邮寄方式已经给大佬发邮件了(一封来自十个月前的邮件回复😆)。
 &gt; Have a nice day!😎
 &gt; 
 &gt; —
 &gt; You are receiving this because you were mentioned.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 92645246464987** [comment]
并没有哦，是回给那位出教程的大佬的
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 286297930 <notifications@github.com&gt;
发送时间: 2019年12月30日 19:08
收件人: david-pzh/A-Eye <A-Eye@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&gt; (#1)



？？？中奖了？？？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"稚晖"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年12月30日(星期一) 晚上6:52 
 收件人:&amp;nbsp;"david-pzh/A-Eye"<A-Eye@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&amp;gt; (#1) 
 
 
 
 ok，这两天会给你发过去 
   
  发自我的iPhone 
   
  &amp;gt; 在 2019年12月28日，下午11:19，IAMLIUBO <notifications@github.com&amp;gt; 写道： 
  &amp;gt;  
  &amp;gt; ﻿ 
  &amp;gt; Hi @david-pzh , 
  &amp;gt; 感谢感谢，我会努力写好的，邮寄方式已经给大佬发邮件了(一封来自十个月前的邮件回复😆)。 
  &amp;gt; Have a nice day!😎 
  &amp;gt;  
  &amp;gt; — 
  &amp;gt; You are receiving this because you were mentioned. 
  &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iamtwvl** [comment]
膜拜大佬，期待教程ing



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 92645246464987 <notifications@github.com&gt;
发送时间: 2019年12月30日 19:11
收件人: david-pzh/A-Eye <A-Eye@noreply.github.com&gt;
抄送: 286297930 <286297930@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&gt; (#1)



并没有哦，是回给那位出教程的大佬的 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 286297930 <notifications@github.com&amp;gt; 
 发送时间: 2019年12月30日 19:08 
 收件人: david-pzh/A-Eye <A-Eye@noreply.github.com&amp;gt; 
 抄送: Subscribed <subscribed@noreply.github.com&amp;gt; 
 主题: 回复：[david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&amp;gt; (#1) 
 
 
 
 ？？？中奖了？？？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"稚晖"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2019年12月30日(星期一) 晚上6:52  
  收件人:&amp;amp;nbsp;"david-pzh/A-Eye"<A-Eye@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [david-pzh/A-Eye] 愿意分享经验、文章报名咯<我不会承认我是为了得到一块PCB！ 滑稽.gif&amp;amp;gt; (#1)  
   
   
   
  ok，这两天会给你发过去  
     
   发自我的iPhone  
     
   &amp;amp;gt; 在 2019年12月28日，下午11:19，IAMLIUBO <notifications@github.com&amp;amp;gt; 写道：  
   &amp;amp;gt;   
   &amp;amp;gt; ﻿  
   &amp;amp;gt; Hi @david-pzh ,  
   &amp;amp;gt; 感谢感谢，我会努力写好的，邮寄方式已经给大佬发邮件了(一封来自十个月前的邮件回复😆)。  
   &amp;amp;gt; Have a nice day!😎  
   &amp;amp;gt;   
   &amp;amp;gt; —  
   &amp;amp;gt; You are receiving this because you were mentioned.  
   &amp;amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe.
